# ***********************
# *** Executable File ***
# ***********************

$(DRACMAPOSITIONMAGNAMENT): $(OBJECT_CPP_FILE_MAIN) $(LIBRARY_FILE_DRACMAAPI) $(LIBRARY_FILE_DRACMAPOSITIONMAGNAMENT_RISK) $(LIBRARY_FILE_DRACMAPOSITIONMAGNAMENT_LOGIC) $(LIBRARY_FILE_DRACMAPOSITIONMAGNAMENT_WEALTH)
	@mkdir -p $(dir $@)
	$(LD) $(LDFLAGS) -o $@ $< $(LDGNUAPI) $(LDDEPEND) $(LDTWS) $(LDDRACMA) $(LDRPATH)

# *****************
# *** Main File ***
# *****************

$(OBJECT_CPP_FILE_MAIN): $(SOURCE_CPP_FILE_MAIN)
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -Os -c -o $@ $<

# *************************
# *** Dynamic Libraries ***
# *************************

$(LIBRARY_FILE_DRACMAAPI): $(FIND_OBJECT_DRACMAAPI_C) $(FIND_OBJECT_DRACMAAPI_CPP) $(FIND_OBJECT_DRACMAAPI_COB)
	@mkdir -p $(dir $@)
	$(LD) $(LDFLAGS) -shared -Wl,-soname,$(shell basename $@) -o $@ $^ $(LDGNUAPI) $(LDDEPEND) $(LDTWS) $(LDRPATH)

$(LIBRARY_FILE_DRACMAPOSITIONMAGNAMENT_RISK): $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_RISK_C) $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_RISK_CPP) $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_RISK_COB)
	@mkdir -p $(dir $@)
	$(LD) $(LDFLAGS) -shared -Wl,-soname,$(shell basename $@) -o $@ $^ $(LDGNUAPI) $(LDDEPEND) $(LDTWS) $(LDRPATH)

$(LIBRARY_FILE_DRACMAPOSITIONMAGNAMENT_LOGIC): $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_LOGIC_C) $(filter-out $(OBJECT_CPP_FILE_MAIN),$(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_LOGIC_CPP)) $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_LOGIC_COB)
	@mkdir -p $(dir $@)
	$(LD) $(LDFLAGS) -shared -Wl,-soname,$(shell basename $@) -o $@ $^ $(LDGNUAPI) $(LDDEPEND) $(LDTWS) $(LDRPATH)

$(LIBRARY_FILE_DRACMAPOSITIONMAGNAMENT_WEALTH): $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_WEALTH_C) $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_WEALTH_CPP) $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_WEALTH_COB)
	@mkdir -p $(dir $@)
	$(LD) $(LDFLAGS) -shared -Wl,-soname,$(shell basename $@) -o $@ $^ $(LDGNUAPI) $(LDDEPEND) $(LDTWS) $(LDRPATH)