# ***********************
# *** Compilers Flags ***
# ***********************

CFLAGS   := -Wall -Wextra -Werror -fPIC -Iinclude -I$(HEADER_FOLDER_TWSSOCKETCLIENT_PROTOBUF)
CXXFLAGS := -Wall -Wextra -Werror -fPIC -Iinclude -I$(HEADER_FOLDER_TWSSOCKETCLIENT_PROTOBUF)
COBFLAGS := -Wall -Wextra -Werror -std=ibm-strict -fstatic-call -Iinclude

# *********************
# *** Linkers Flags ***
# *********************

LDFLAGS :=	-L$(LIBRARY_FOLDER_DEPEND_CJSON) -L$(LIBRARY_FOLDER_DEPEND_DB) -L$(LIBRARY_FOLDER_DEPEND_LZMA) -L$(LIBRARY_FOLDER_DEPEND_XML2) -L$(LIBRARY_FOLDER_DEPEND_ZLIB) \
			-L$(LIBRARY_FOLDER_GNUAPI_CSTD) -L$(LIBRARY_FOLDER_GNUAPI_GMP) -L$(LIBRARY_FOLDER_GNUAPI_LIBCOB) -L$(LIBRARY_FOLDER_GNUAPI_NCURSESW) -L$(LIBRARY_FOLDER_GNUAPI_TINFO) \
			-L$(LIBRARY_FOLDER_DRACMAAPI) -L$(LIBRARY_FOLDER_DRACMAPOSITIONMAGNAMENT) \
			-L$(LIBRARY_FOLDER_TWSSOCKETCLIENT)

LDTWS    := -lTwsSocketClient
LDGNUAPI := -lcob -lc -lgmp -lncursesw -ltinfo -lm
LDDEPEND := -lxml2 -ldb -lz -llzma
LDDRACMA := -lDracmaApi -lDPMRisk -lDPMLogic -lDPMWealth

LDRPATH  :=	-Wl,-rpath,"$(LIBRARY_FOLDER_DEPEND_CJSON):$(LIBRARY_FOLDER_DEPEND_DB):$(LIBRARY_FOLDER_DEPEND_LZMA):$(LIBRARY_FOLDER_DEPEND_XML2):$(LIBRARY_FOLDER_DEPEND_ZLIB):$(LIBRARY_FOLDER_GNUAPI_CSTD):$(LIBRARY_FOLDER_GNUAPI_GMP):$(LIBRARY_FOLDER_GNUAPI_LIBCOB):$(LIBRARY_FOLDER_GNUAPI_NCURSESW):$(LIBRARY_FOLDER_GNUAPI_TINFO):$(LIBRARY_FOLDER_DRACMAAPI):$(LIBRARY_FOLDER_DRACMAPOSITIONMAGNAMENT):$(LIBRARY_FOLDER_TWSSOCKETCLIENT)"

# ***********************
# *** Utilities Flags ***
# ***********************

ARFLAGS := rcs
LNFLAGS := -s