# *************
# *** Rules ***
# *************

all:	$(OBJECT_CPP_FILE_MAIN) \
		$(FIND_OBJECT_DRACMAAPI_C) $(FIND_OBJECT_DRACMAAPI_CPP) $(FIND_OBJECT_DRACMAAPI_COB) \
		$(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_RISK_C) $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_RISK_CPP) $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_RISK_COB) \
		$(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_LOGIC_C) $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_LOGIC_CPP) $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_LOGIC_COB) \
		$(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_WEALTH_C) $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_WEALTH_CPP) $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_WEALTH_COB) \
		$(LIBRARY_FILE_DRACMAAPI) $(LIBRARY_FILE_DRACMAPOSITIONMAGNAMENT_RISK) $(LIBRARY_FILE_DRACMAPOSITIONMAGNAMENT_LOGIC) $(LIBRARY_FILE_DRACMAPOSITIONMAGNAMENT_WEALTH) \
		$(DRACMAPOSITIONMAGNAMENT)

run: $(DRACMAPOSITIONMAGNAMENT)
	@./$<

ldd: $(DRACMAPOSITIONMAGNAMENT)
	@ldd ./$<

clean:
	$(RM) $(OBJECT_CPP_FILE_MAIN)
	$(RM) $(FIND_OBJECT_DRACMAAPI_C) $(FIND_OBJECT_DRACMAAPI_CPP) $(FIND_OBJECT_DRACMAAPI_COB)
	$(RM) $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_RISK_C) $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_RISK_CPP) $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_RISK_COB)
	$(RM) $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_LOGIC_C) $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_LOGIC_CPP) $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_LOGIC_COB)
	$(RM) $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_WEALTH_C) $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_WEALTH_CPP) $(FIND_OBJECT_DRACMAPOSITIONMAGNAMENT_WEALTH_COB)
	$(RM) $(LIBRARY_FILE_DRACMAAPI) $(LIBRARY_FILE_DRACMAPOSITIONMAGNAMENT_RISK) $(LIBRARY_FILE_DRACMAPOSITIONMAGNAMENT_LOGIC) $(LIBRARY_FILE_DRACMAPOSITIONMAGNAMENT_WEALTH)
	$(RM) $(DRACMAPOSITIONMAGNAMENT)

cleandist:
	rm -rf build *.json